name: starter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # network
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.2.1
  logger: any

  # state management
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6

  # validator
  form_validator: ^2.1.1

  # cache
  shared_preferences: ^2.1.2

  # router
  auto_route: ^7.4.0

  # ui
  gap: ^2.0.1
  google_fonts: ^5.0.0

  # pagination
  infinite_scroll_pagination: ^3.2.0

  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
